bajesova formula: $ P(y | x) = \frac{P(x | y)*P(y)}{P(x)} $

categorical naive bayes - pp da su Xi uslovno nezavisni
nezavisni: $ P(X,Y) = P(X)P(Y) $
uslovno nez: $ P(X1,X2|Y) = P(X1|Y)P(X2|Y) $
smoothing laplas? Ostavicemo uvek neku malu verovatnocu da (ne)ce se nesto desiti (0+ e, 1 - e)

In [1]:
import pandas as pd

In [59]:
import numpy as np

In [36]:
df = pd.read_csv('data/balloons.csv') #nisam uspeo da nadjem ballons skup -.-

In [37]:
df.head

<bound method NDFrame.head of      color   size      act    age inflated
0   YELLOW  SMALL  STRETCH  ADULT        T
1   YELLOW  SMALL  STRETCH  ADULT        T
2   YELLOW  SMALL  STRETCH  CHILD        F
3   YELLOW  SMALL      DIP  ADULT        F
4   YELLOW  SMALL      DIP  CHILD        F
..     ...    ...      ...    ...      ...
71  PURPLE  SMALL      DIP  CHILD        F
72  PURPLE  LARGE  STRETCH  ADULT        F
73  PURPLE  LARGE  STRETCH  CHILD        F
74  PURPLE  LARGE      DIP  ADULT        F
75  PURPLE  LARGE      DIP  CHILD        F

[76 rows x 5 columns]>

In [38]:
X = df[df.columns[:-1]]

In [39]:
print(X.describe())

         color   size      act    age
count       76     76       76     76
unique       2      2        2      2
top     YELLOW  SMALL  STRETCH  ADULT
freq        40     40       38     38


In [41]:
y = df.iloc[:, -1]
y.shape

(76,)

In [42]:
from sklearn.model_selection import train_test_split

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=1/3, random_state=13, stratify=y)

In [44]:
X_train.shape

(50, 4)

In [45]:
y_train.shape

(50,)

In [46]:
X_test.shape

(26, 4)

In [47]:
from sklearn.naive_bayes import CategoricalNB

In [53]:
from sklearn.preprocessing import OrdinalEncoder

In [54]:
oe = OrdinalEncoder()

In [56]:
oe.fit(X_train)

,categories,'auto'
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,unknown_value,None
,encoded_missing_value,nan
,min_frequency,None
,max_categories,None


In [58]:
oe.categories_

[array(['PURPLE', 'YELLOW'], dtype=object),
 array(['LARGE', 'SMALL'], dtype=object),
 array(['DIP', 'STRETCH'], dtype=object),
 array(['ADULT', 'CHILD'], dtype=object)]

In [62]:
X_train = oe.transform(X_train)

In [63]:
X_test = oe.transform(X_test)

In [48]:
model = CategoricalNB()

In [70]:
model.fit(X_train, y_train)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None
,min_categories,None


In [73]:
y_train_predict = model.predict(X_train)

In [66]:
from sklearn.metrics import confusion_matrix

In [74]:
confusion_matrix(y_train, y_train_predict)

array([[21,  6],
       [ 6, 17]])

In [75]:
y_test_predicted = model.predict(X_test)

In [76]:
confusion_matrix(y_test, y_test_predicted)

array([[12,  2],
       [ 2, 10]])

In [77]:
from sklearn.pipeline import Pipeline

In [84]:
pipe = Pipeline([('ordinal encoder', OrdinalEncoder()), ('classifier', CategoricalNB())])

In [85]:
pipe.fit(X_train,y_train)

,steps,"[('ordinal encoder', ...), ('classifier', ...)]"
,transform_input,None
,memory,None
,verbose,False
,categories,'auto'
,dtype,<class 'numpy.float64'>
,handle_unknown,'error'
,unknown_value,None
,encoded_missing_value,nan
,min_frequency,None
,max_categories,None


In [13]:
print(X.head())

    color   size      act    age
0  YELLOW  SMALL  STRETCH  ADULT
1  YELLOW  SMALL  STRETCH  ADULT
2  YELLOW  SMALL  STRETCH  ADULT
3  YELLOW    NaN  STRETCH  ADULT
4  YELLOW  SMALL  STRETCH  ADULT


In [15]:
X.shape

(100, 4)

In [87]:
corpus = ['Chinese Bejing chinese','Chinese Chinese Shanghai','Chinese Makao', 'Tokyo Japan Chinese']
classes = ['yes','yes','yes','no']

In [86]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfTransformer, TfidfVectorizer

In [88]:
vectorizer = TfidfVectorizer()
# TfidfVectorizer == CountVectorizer . tfidfTransformer

In [89]:
vectorizer.fit(corpus)

,input,'content'
,encoding,'utf-8'
,decode_error,'strict'
,strip_accents,None
,lowercase,True
,preprocessor,None
,tokenizer,None
,analyzer,'word'
,stop_words,None
,token_pattern,'(?u)\\b\\w\\w+\\b'
,ngram_range,"(1, ...)"


In [90]:
X_train = vectorizer.transform(corpus)

In [91]:
X_train.toarray()

array([[0.69183461, 0.722056  , 0.        , 0.        , 0.        ,
        0.        ],
       [0.        , 0.722056  , 0.        , 0.        , 0.69183461,
        0.        ],
       [0.        , 0.46263733, 0.        , 0.88654763, 0.        ,
        0.        ],
       [0.        , 0.34618161, 0.66338461, 0.        , 0.        ,
        0.66338461]])

In [92]:
vectorizer.get_feature_names_out()

array(['bejing', 'chinese', 'japan', 'makao', 'shanghai', 'tokyo'],
      dtype=object)

In [93]:
X_train = pd.DataFrame(X_train.toarray(),columns=vectorizer.get_feature_names_out())

In [95]:
print(X_train)

     bejing   chinese     japan     makao  shanghai     tokyo
0  0.691835  0.722056  0.000000  0.000000  0.000000  0.000000
1  0.000000  0.722056  0.000000  0.000000  0.691835  0.000000
2  0.000000  0.462637  0.000000  0.886548  0.000000  0.000000
3  0.000000  0.346182  0.663385  0.000000  0.000000  0.663385


naive bayes multinomial
koristi se za tekst

In [96]:
from sklearn.naive_bayes import MultinomialNB

In [98]:
model = MultinomialNB()

In [15]:
type(classes)

list

In [99]:
vectorizer = CountVectorizer()
X_train = vectorizer.fit_transform(corpus)

model = MultinomialNB()
model.fit(X_train, classes)

,alpha,1.0
,force_alpha,True
,fit_prior,True
,class_prior,None


In [100]:
model.classes_

array(['no', 'yes'], dtype='<U3')

In [101]:
doc = 'Chinese','Chinese','Chinese','Tokyo','Japan'

In [102]:
x_test = vectorizer.transform(doc)

In [103]:
pred = model.predict(x_test)

In [105]:
confusion_matrix(pred,classes)

ValueError: Found input variables with inconsistent numbers of samples: [5, 4]